apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cfahrni-app-of-apps-4
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cfahrni
    name: in-cluster
  project: default
  source:
    path: app-of-apps-applications/app4
    repoURL: https://github.com/cfahrni/argocd-training-examples.git
    targetRevision: HEAD
